# -*- coding: utf-8 -*-
"""BA_Assignment02_Group01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bPoF7R_4TysaY1vj_popiAYG2yjsIyao
"""

import streamlit as st
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score, accuracy_score, average_precision_score, mean_absolute_error

st.set_page_config(page_title='Churn decision support', page_icon='📺', layout='wide')
st.title('Customer Churn Decision Support')

@st.cache_data
def load_data():
    data = pd.read_csv('netflix_customer_churn.csv')
    if data['churned'].isna().any() or not set(data['churned'].unique()).issubset({0, 1}):
        raise ValueError('Churn must contain only 0 and 1, without missing values.')
    return data

@st.cache_resource
def train_models(data):
    excluded = {'customer_id', 'churned', 'avg_watch_time_per_day', 'monthly_fee'}
    features = [c for c in data.columns if c not in excluded]
    X = data[features]
    y = data['churned'].astype(int)
    nums = X.select_dtypes(include='number').columns.tolist()
    cats = X.select_dtypes(exclude='number').columns.tolist()
    prep = ColumnTransformer([
        ('num', Pipeline([('fill', SimpleImputer(strategy='median')), ('scale', StandardScaler())]), nums),
        ('cat', Pipeline([('fill', SimpleImputer(strategy='most_frequent')), ('encode', OneHotEncoder(handle_unknown='ignore'))]), cats)
    ])
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, stratify=y, random_state=42)
    models = {
        'Logistic regression': Pipeline([('prep', prep), ('model', LogisticRegression(max_iter=2000))]),
        'Linear regression (benchmark)': Pipeline([('prep', prep), ('model', LinearRegression())]),
        'Random forest': Pipeline([('prep', prep), ('model', RandomForestClassifier(n_estimators=200, min_samples_leaf=10, random_state=42, n_jobs=-1))])
    }
    results = []
    for name, model in models.items():
        model.fit(X_train, y_train)
        raw = model.predict(X_test) if name.startswith('Linear') else model.predict_proba(X_test)[:, 1]
        score = np.clip(raw, 0, 1) if name.startswith('Linear') else raw
        results.append({'Model': name, 'ROC-AUC': roc_auc_score(y_test, score),
                        'PR-AUC': average_precision_score(y_test, score),
                        'Accuracy at 0.5': accuracy_score(y_test, score >= 0.5),
                        'Mean Absolute Error': mean_absolute_error(y_test, score)})
    return models, pd.DataFrame(results), features, nums, cats

try:
    df = load_data()
    models, report, features, nums, cats = train_models(df)
except Exception as exc:
    st.error(f'Could not prepare app: {exc}')
    st.stop()

st.info('Use the profile controls to estimate churn risk. Churn=1 means the customer churned in the dataset.')

with st.sidebar:
    st.header('Customer profile')
    inputs = {}
    for col in features:
        if col in nums:
            inputs[col] = st.number_input(col.replace('_', ' ').title(), value=float(df[col].median()), step=1.0)
        else:
            inputs[col] = st.selectbox(col.replace('_', ' ').title(), sorted(df[col].dropna().astype(str).unique()))
    threshold = st.slider('Review threshold', 0.05, 0.95, 0.50, 0.05)
    predict = st.button('Predict churn', type='primary')

if predict:
    row = pd.DataFrame([inputs])[features]
    logistic = float(models['Logistic regression'].predict_proba(row)[0, 1])
    forest = float(models['Random forest'].predict_proba(row)[0, 1])
    linear_raw = float(models['Linear regression (benchmark)'].predict(row)[0])
    a, b, c = st.columns(3)
    a.metric('Logistic churn score', f'{logistic:.1%}')
    b.metric('Random forest churn score', f'{forest:.1%}')
    c.metric('Linear benchmark (clipped)', f'{np.clip(linear_raw, 0, 1):.1%}')
    if logistic >= threshold:
        st.warning('Flag for manager review: Investigate engagement and appropriate retention options. Do not automatically send an offer.')
    else:
        st.success('Below the selected review threshold; continue routine monitoring.')
    st.caption('The linear score is not a calibrated probability. A high churn score does not prove a proposed intervention will work.')

st.body('Churn Score Categories and Suggestions')
st.markdown("""
| Logistic Churn Score | Category | Suggestion |
|---|---|---|
| 0% to under 40% | Low | Routine monitoring |
| 40% to under 70% | Medium | Check engagement; consider low-cost outreach |
| 70% to 100% | High | Prioritise for human review |
""")
